
source 'https://github.com/CocoaPods/Specs.git'
# 增加私有资源库地址
source 'https://gitlab.ad-mex.com/app/Module_iOS.git'
platform :ios, '9.0'

# 消除所有警告
inhibit_all_warnings!

install! 'cocoapods',
# 生成多个 Xcodeproj
:generate_multiple_pod_projects => true,
# 支持增量安装
:incremental_installation => true

#use_frameworks!

target 'MEGDTAdapter_Example' do
  pod 'MEGDTAdapter', :path => '../'

  target 'MEGDTAdapter_Tests' do
    inherit! :search_paths

    
  end
end
